development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: set_app_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: set_app_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: set_app_rails
  pool: 5
  timeout: 5000